export const food=[
    {   "id":1,
        "title":"Dijon & Panko-Crusted Lamb Chops",
        "subtitle": "with Salsa Verde Carrots & Garlicky Purple Potatoes",
        "time":"55 min",
        "price":"$19.99/SERVING",
        "servings":"2 Servings", 
        "calories":"940 Cals/serving", 
        "image": "https://media.blueapron.com/recipes/25448/square_newsletter_images/1601348202-32-0039-4337/1102_2P12_Herb-Crusted-Lamb_374_SQ_Web.jpg", 
        "ingredients":
            [   {"qty": "1","name":"Frenched Rack Of Lamb"},
                {"qty":"6 oz","name": "Carrots"},
                {"qty":"3/4 lb","name":"Purple Potatoes"},
                {"qty":"1","name":"Lemon"},
                {"qty":"2 cloves", "name": "Garlic"},
                {"qty":"1 bunch", "name": "Thyme"},
                {"qty":"1 bunch", "name": "Oregano"},
                {"qty":"1/4 cup", "name": "Panko Breadcrumbs"},
                {"qty":"1 Tbsp", "name": "Dijon Mustard"},
                {"qty":"1/3 cup", "name": "Salsa Verde"},
                {"qty":"0.7 oz", "name": "Grana Padano Cheese"},
                {"qty":"2 Tbsps", "name": "Crème Fraiche"},
                {"qty":"1 oz", "name": "Castelvetrano Olives"}
            ],
        "ingredientsImg":"https://media.blueapron.com/recipes/25448/ingredient_images/1601659427-32-0002-5216/1102_2PRE12_large_feature.png",
        "steps":
            [   {"number":"1","desc":"Prepare the ingredients", 
                "step":"Preheat the oven to 450°F. Wash and dry the fresh produce. Peel the carrots; halve lengthwise, then halve crosswise. Halve the potatoes lengthwise; cut crosswise into 1/4-inch pieces. Pick the thyme leaves off the stems. Quarter and deseed the lemon. Peel 2 cloves of garlic; using a zester, finely grate into a paste (or use the small side of a box grater). Pick the oregano leaves off the stems; finely chop. Pit and roughly chop the olives. Grate the cheese on the small side of a box grater. In a bowl, combine the breadcrumbs, thyme leaves, half the garlic paste, half the mustard, and 2 teaspoons of olive oil; season with salt and pepper. To make the garlic dressing, in a separate, large  bowl, combine the chopped oregano, chopped olives, remaining garlic paste, the juice of 2 lemon wedges, and a drizzle of olive oil; season with salt and pepper. In a separate bowl, combine the crème fraîche and salsa verde.",
                "img":"https://media.blueapron.com/recipes/25448/recipe_steps/48670/1601348264-33-0037-6769/1102_2P12_Herb-Crusted-Lamb_102_Web.jpg"}, 
                {"number":"2","desc":"Prepare & roast the lamb",
                "step":"Line a sheet pan with foil. Pat the lamb dry with paper towels; season with salt and pepper on all sides. Place on the sheet pan, bone side down. Evenly spread or brush the remaining mustard onto the top side of the lamb (opposite of the bones), then top with the breadcrumb mixture (pressing to adhere). Roast 27 to 29 minutes for medium (125°F), or until cooked to your desired degree of doneness.* Transfer to a cutting board and let rest at least 10 minutes.*The USDA recommends cooking lamb until an instant-read thermometer registers a minimum temperature of 145°F.",
                "img":"https://media.blueapron.com/recipes/25448/recipe_steps/48671/1601348259-33-0036-5606/1102_2P12_Herb-Crusted-Lamb_103_Web.jpg"},
                {"number":"3","desc":"Roast the vegetables",
                "step":"Meanwhile, transfer the carrot pieces to one side of a separate sheet pan; place the potato pieces on the other side. Drizzle with olive oil and season with salt and pepper. Toss to coat; keeping them separate on the sheet pan, arrange in an even layer. Roast 20 to 22 minutes, or until browned and tender when pierced with a fork. Remove from the oven.",
                "img":"https://media.blueapron.com/recipes/25448/recipe_steps/48672/1601348255-32-0040-6043/1102_2P12_Herb-Crusted-Lamb_104_Web.jpg"},
                {"number":"4","desc":"Dress the vegetables",
                "step":"Transfer the roasted carrots to a large bowl; add half the creamy salsa verde. Toss to coat. Taste, then season with salt and pepper if desired. Transfer the roasted potatoes to the bowl of garlic dressing; add the grated cheese. Toss to combine. Taste, then season with salt and pepper if desired.",
                "img":"https://media.blueapron.com/recipes/25448/recipe_steps/48673/1601348239-33-0035-0638/1102_2P12_Herb-Crusted-Lamb_105_Web.jpg"},
                {"number":"5","desc":"Slice the lamb & serve your dish",
                "step":"Slice the rested lamb  between each bone. Serve the sliced lamb with the remaining creamy salsa verde. Serve the dressed carrots, dressed potatoes, and remaining lemon wedges on the side. Enjoy!",
                "img":"https://media.blueapron.com/recipes/25448/recipe_steps/48674/1601348235-32-0042-5502/1102_2P12_Herb-Crusted-Lamb_106_Web.jpg"}
            ],
        "special":"false"
    },
    {   "id":2,
        "title":"Calabrian Shrimp & Orzo",
        "subtitle":"with Tomatoes & Parmesan Cheese",
        "time":"20 min",
        "price":"600 Calories Or Less",
        "servings":"2 Servings",
        "calories":"500 Cals/serving",
        "image":"https://media.blueapron.com/recipes/25451/square_newsletter_images/1603459980-33-0011-6659/1102_2PF_Shrimp_0480_SQ_Web.jpg",
        "ingredients":
        [   {"qty":"10 oz","name":"Tail-On Shrimp (Peeled & Deveined)"},
            {"qty":"4 oz","name":"Orzo Pasta"},
            {"qty":"2 cloves","name":"Garlic"},
            {"qty":"1","name":"Lemon"},
            {"qty":"1.5 tsps","name":"Calabrian Chile Paste"},
            {"qty":"2 Tbsps","name":"Crème Fraîche"},
            {"qty":"1 Tbsp","name":"Capers"},
            {"qty":"1/4 cup","name":"Grated Parmesan Cheese"},
            {"qty":"4 oz","name":"Grape Tomatoes"}
        ],
        "ingredientsImg":"https://media.blueapron.com/recipes/25451/ingredient_images/1601343193-32-0003-8741/1102_2PF_large_feature.png",
        "steps":
        [   {"number":"1","desc":"Prepare the ingredients",
            "step":"Fill a medium pot 3/4 of the way up with salted water; cover and heat to boiling on high. Wash and dry the fresh produce. Halve the tomatoes. Quarter and deseed the lemon. Peel and roughly chop 2 cloves of garlic. Pat the shrimp dry with paper towels; remove the tails. Place in a bowl; add the chopped garlic, capers, and as much of the chile paste as you’d like, depending on how spicy you’d like the dish to be. Drizzle with olive oil and season with salt and pepper. Stir to combine.",
            "img":"https://media.blueapron.com/recipes/25451/recipe_steps/48046/1601415440-33-0003-2981/1102_2PF_Calabrian-Shrimp-Orzo_102_Web_Tomato.jpg"},
            {"number":"2","desc":"Cook the pasta",
            "step":"Add the pasta to the pot of boiling water and cook, uncovered, 7 to 9 minutes, or until tender. Turn off the heat. Drain thoroughly and return to the pot.",
            "img":"https://media.blueapron.com/recipes/25451/recipe_steps/48047/1601343371-32-0010-5622/0121_2PF-WW2_Shrimp-Orzo_0541_Web.jpg"},
            {"number":"3","desc":"Cook the shrimp & tomatoes",
            "step":"Meanwhile, in a large pan (nonstick, if you have one), heat 2 teaspoons of olive oil on medium-high until hot. Add the prepared shrimp in an even layer. Cook, without stirring, 2 to 3 minutes, or until lightly browned. Add the halved tomatoes. Cook, stirring frequently, 1 to 2 minutes, or until the shrimp are opaque and cooked through. Turn off the heat.",
            "img":"https://media.blueapron.com/recipes/25451/recipe_steps/48048/1603459993-32-0013-9081/1102_2PF_Shrimp_0477_Web.jpg"},
            {"number":"4","desc":"Finish & serve your dish",
            "step":"To the pot of cooked pasta, add the cooked shrimp and tomatoes, crème fraîche, and the juice of 2 lemon wedges. Stir to combine. Taste, then season with salt and pepper if desired. Serve the finished shrimp and pasta garnished with the cheese and remaining lemon wedges. Enjoy!",
            "img":"https://media.blueapron.com/recipes/25451/recipe_steps/48050/1603460000-33-0012-4002/1102_2PF_Shrimp_0482_Web.jpg"}
        ],
        "special":"true"
    },
    {   "id":3,
        "title":"Mongolian Beef & Noodles",
        "subtitle":"with Shishito Peppers & Scallions",
        "time":"25 min",
        "servings":"2 Servings",
        "calories":"650 Cals/serving",
        "image":"https://media.blueapron.com/recipes/25450/square_newsletter_images/1603459639-32-0007-3159/1102_2P11_Mongolian-Beef_0489_SQ_Web.jpg",
        "ingredients":
        [   {"qty":"8 oz","name":"Thinly Sliced Beef"},
            {"qty":"6 oz","name":"Fresh Wonton Noodles (PreviouslyFrozen)"},
            {"qty":"2 cloves","name":"Garlic"},
            {"qty":"2","name":"Scallions"},
            {"qty":"1 Tbsp","name":"Soy Sauce"},
            {"qty":"1 Tbsp","name":"Light Brown Sugar"},
            {"qty":"1/4 cup","name":"Cornstarch"},
            {"qty":"1","name":"Piece Ginger"},
            {"qty":"2 Tbsps","name":"Chicken Demi-Glace"},
            {"qty":"3 oz","name":"Shishito Peppers"},
            {"qty":"1/4 tsp","name":"Crushed Red Pepper Flakes"}
        ],
        "ingredientsImg":"https://media.blueapron.com/recipes/25450/ingredient_images/1601387630-32-0071-9898/1102_2PRE11_large_feature.png",
        "steps":
        [   {"number":"1","desc":"Prepare the ingredients",
            "step":"Fill a medium pot 3/4 of the way up with salted water; cover and heat to boiling on high. Wash and dry the fresh produce. Peel and roughly chop 2 cloves of garlic. Peel the ginger; finely chop to get 2 teaspoons (you may have extra). Slice the scallions into 1/2-inch pieces, separating the white bottoms and hollow green tops. Cut off and discard the stems of the peppers; cut crosswise into 1/2-inch pieces. Thoroughly wash your hands, knife, and cutting board immediately after handling. Place the pepper pieces in a bowl; add the chopped garlic, chopped ginger, and sliced white bottoms of the scallions.",
            "img":"https://media.blueapron.com/recipes/25450/recipe_steps/48040/1603459664-33-0007-3219/1102_2P11_Mongolian-Beef_0473_Web.jpg"},
            {"number":"2","desc":"Make the sauce",
            "step":"In a bowl, combine the soy sauce, demi-glace, sugar, 1/3 cup of water, and as much of the red pepper flakes as you’d like, depending on how spicy you’d like the dish to be.",
            "img":"https://media.blueapron.com/recipes/25450/recipe_steps/48041/1601387551-32-0072-3247/1019_FP5_Mongolian-Beef_028_Web.jpg"},
            {"number":"3","desc":"Cook the peppers",
            "step":"In a medium pan (nonstick, if you have one), heat 2 teaspoons of olive oil on medium-high until hot. Add the prepared pepper mixture; season with salt and pepper. Cook, stirring frequently, 3 to 4 minutes, or until softened. Transfer to a plate. Wipe out the pan.",
            "img":"https://media.blueapron.com/recipes/25450/recipe_steps/48042/1603459683-32-0008-0191/1102_2P11_Mongolian-Beef_0478_Web.jpg"},
            {"number":"4","desc":"Cook the beef",
            "step":"Separate the beef; pat dry with paper towels. Place in a bowl and season with salt and pepper. Add the cornstarch; toss to thoroughly coat. In the same pan, heat 2 teaspoons of olive oil on medium-high. Once the oil is hot enough that a pinch of cornstarch sizzles immediately when added, add the coated beef in an even layer (discarding any excess cornstarch). Cook, without stirring, 2 to 3 minutes, or until lightly browned. Continue to cook, stirring frequently, 1 to 2 minutes, or until browned and just cooked through. Turn off the heat.",
            "img":"https://media.blueapron.com/recipes/25450/recipe_steps/48043/1601660392-34-0004-0013/1028_2PRE10_WW05_Spicy-Pepper-Beef_120_Web.jpg"},
            {"number":"5","desc":"Cook the noodles",
            "step":"Meanwhile, add the noodles to the pot of boiling water, stirring gently to separate. Cook, stirring occasionally, 2 to 4 minutes, or until tender. Turn off the heat. Drain thoroughly and return to the pot.",
            "img":"https://media.blueapron.com/recipes/25450/recipe_steps/48044/1601387535-32-0068-3165/1019_FP5_Mongolian-Beef_044_Web.jpg"},
            {"number":"6","desc":"Finish the noodles & serve your dish",
            "step":"To the pot of cooked noodles, add the cooked vegetables, cooked beef, and sauce. Cook on medium-high, stirring constantly, 1 to 2 minutes, or until coated. Turn off the heat; taste, then season with salt and pepper if desired. Serve the finished noodles garnished with the sliced green tops of the scallions. Enjoy!",
            "img":"https://media.blueapron.com/recipes/25450/recipe_steps/48045/1603459691-32-0009-1382/1102_2P11_Mongolian-Beef_0481_Web.jpg"}
        ],
        "special":"false"
    },
    {   "id":4,
        "title":"Honey Mustard Baked Chicken",
        "subtitle":"with Smoky Smashed Potatoes",
        "time":"40 min",
        "price":"600 Calories Or Less",
        "servings":"2 Servings",
        "calories":"590 Cals/serving",
        "image":"https://media.blueapron.com/recipes/25249/square_newsletter_images/1601342433-33-0005-1644/1102_2PP_Honey-Mustard-Chicken_453_203_SQ_Web.jpg",
        "ingredients":
        [   {"qty":"2","name":"Boneless, Skinless Chicken Breasts"},
            {"qty":"3/4 lb","name":"Golden Potatoes"},
            {"qty":"1 bunch","name":"Collard Greens"},
            {"qty":"2 tsps","name":"Honey"},
            {"qty":"1/4 cup","name":"Panko Breadcrumbs"},
            {"qty":"1/4 cup","name":"Sour Cream"},
            {"qty":"1 Tbsp","name":"Apple Cider Vinegar"},
            {"qty":"1","name":"Shallot"},
            {"qty":"1 oz","name":"Sliced Roasted Red Peppers"},
            {"qty":"2 Tbsps","name":"Sweet Pickle Relish"},
            {"qty":"1 Tbsp","name":"Smoky Spice Blend (Smoked Paprika, Sweet Paprika, Ground Yellow Mustard, Garlic Powder & Onion Powder)"},
            {"qty":"1 Tbsp","name":"Dijon Mustard"}
        ],
        "ingredientsImg": "https://media.blueapron.com/recipes/25249/ingredient_images/1601343027-33-0006-5927/1102_2PP_large_feature.png",
        "steps":
        [   {"number":"1","desc":"Prepare the ingredients & make the pepper relish",
            "step":"Remove the honey from the refrigerator to bring to room temperature. Place an oven rack in the center of the oven, then preheat to 450°F. Fill a medium pot 3/4 of the way up with salted water; cover and heat to boiling on high. Wash and dry the fresh produce. Large dice the potatoes. Separate the collard green leaves from the stems; discard the stems, then roughly chop the leaves. Peel and thinly slice the shallot. Roughly chop the peppers; place in a bowl. Add the relish and stir to combine.",
            "img":"https://media.blueapron.com/recipes/25249/recipe_steps/48032/1601342684-32-0007-1269/1102_2PP_Honey-Mustard-Chicken_605_Web.jpg"},
            {"number":"2","desc":"Cook & smash the potatoes",
            "step":"Add the diced potatoes to the pot of boiling water. Cook 17 to 19 minutes, or until tender when pierced with a fork. Turn off the heat. Drain thoroughly and return to the pot. Add the sour cream, half the spice blend, and 1 teaspoon of olive oil; stir gently to combine. Using a fork or potato masher, lightly smash the potatoes. Taste, then season with salt and pepper if desired. Cover to keep warm.",
            "img":"https://media.blueapron.com/recipes/25249/recipe_steps/48031/1601342671-32-0006-9863/1102_2PP_Honey-Mustard-Chicken_627_Web.jpg"},
            {"number":"3","desc":"Prepare the collard green foil packet",
            "step":"Meanwhile, line a sheet pan with foil. Place a separate large, rectangular piece of foil on a work surface. In a large bowl, combine the chopped collard greens, sliced shallot, and 1 teaspoon of olive oil; season with salt and pepper. Stir to thoroughly combine. Transfer to one side of the foil piece; top with 1 tablespoon of water. Fold the foil in half over the prepared collard greens. Roll and crimp the 3 open edges inwards to completely seal the packet. Transfer to one side of the sheet pan.",
            "img":"https://media.blueapron.com/recipes/25249/recipe_steps/48030/1601342658-32-0005-4422/1102_2PP_Honey-Mustard-Chicken_610_Web.jpg"},
            {"number":"4","desc": "Prepare & bake the chicken",
            "step":"In a bowl, whisk together the honey (kneading the packet before opening) and  mustard. In a separate bowl, combine the breadcrumbs and 2  teaspoons of olive oil; season with salt and pepper. Pat the chicken dry with paper towels; season on both sides with salt, pepper, and  the remaining spice blend. Transfer to the other side of the sheet pan of prepared collard greens. Evenly spread or brush the honey mustard onto the chicken, then top with the seasoned breadcrumbs (pressing to adhere). Bake the chicken and collard greens 19 to 21 minutes, or until the topping is browned and the chicken is cooked through.* Remove from the oven. *An instant-read thermometer should register 165°F.",
            "img":"https://media.blueapron.com/recipes/25249/recipe_steps/48033/1601342647-32-0004-8544/1102_2PP_Honey-Mustard-Chicken_616_Web.jpg"},
            {"number":"5","desc":"Finish the collard greens & serve your dish",
            "step":"Carefully open the packet of cooked collard greens; stir in the vinegar. Taste, then season with salt and pepper if desired. Serve the baked chicken with the smashed potatoes and finished collard greens. Garnish the chicken with pepper relish. Enjoy!",
            "img":"https://media.blueapron.com/recipes/25249/recipe_steps/48034/1601342608-32-0003-9819/1102_2PP_Honey-Mustard-Chicken_639_Web.jpg"}
        ],
        "special":"false"
    },
    {   "id":5,
        "title":"Hot Italian Pork Sausage & Brussels Sprouts",
        "subtitle":"with Bucatini Pasta",
        "time":"20 min",
        "servings":"2 Servings",
        "calories":"850 Cals/serving",
        "image":"https://media.blueapron.com/recipes/25456/square_newsletter_images/1601389502-32-0081-8568/1209_2P8_Pork-Pasta_9588_SQ_Web.jpg",
        "ingredients":
        [   {"qty":"10 oz","name":"Hot Italian Pork Sausage"},
            {"qty":"1/2 lb","name":"Bucatini Pasta"},
            {"qty":"4 oz","name":"Brussels Sprouts"},
            {"qty":"2 cloves","name":"Garlic"},
            {"qty":"1","name":"Yellow Onion"},
            {"qty":"1 Tbsp","name":"Apple Cider Vinegar"},
            {"qty":"2 Tbsps","name":"Mascarpone Cheese"},
            {"qty":"1/4 cup","name":"Grated Parmesan Cheese"}
        ],
        "ingredientsImg":"https://media.blueapron.com/recipes/25456/ingredient_images/1601388939-32-0079-6144/1102_2PRE08_large_feature.png",
        "steps":
        [   {"number":"1","desc":"Prepare the ingredients",
            "step":"Fill a large pot 3/4 of the way up with salted water; cover and heat to boiling on high. Wash and dry the brussels sprouts; cut off and discard the stem ends. Halve lengthwise, then thinly slice crosswise. Halve, peel, and thinly slice the onion. Peel and roughly chop 2 cloves of garlic. Combine the sliced brussels sprouts, sliced onion, and chopped garlic in a bowl.",
            "img":"https://media.blueapron.com/recipes/25456/recipe_steps/48068/1601389948-33-0077-6609/1209_2P8_Pork-Pasta_380_Web.jpg"},
            {"number":"2","desc":"Cook the pasta",
            "step":"Add the pasta to the pot of boiling water. Cook, stirring occasionally, 6 to 8 minutes, or until al dente (still slightly firm to the bite). Turn off  the heat. Reserving 1 1/2 cups of the pasta cooking water, drain thoroughly and return to the pot.",
            "img":"https://media.blueapron.com/recipes/25456/recipe_steps/48069/1601389943-32-0082-6378/1209_2P8_Pork-Pasta_382_Web.jpg"},
            {"number":"3","desc":"Cook the sausage & vegetables",
            "step":"Meanwhile, in a large pan, heat a drizzle of olive oil on medium-high until hot. Add the sausage. Cook, stirring frequently and breaking the meat apart with a spoon, 3 to 4 minutes, or until browned. Add the prepared vegetables. Cook, stirring frequently, 4 to 5 minutes, or until softened and the sausage is cooked through. Add the vinegar (carefully, as the liquid may splatter). Cook, stirring frequently and scraping up any browned bits (or fond), 30 seconds to 1 minute, or until the liquid has cooked off. Turn off the heat.",
            "img":"https://media.blueapron.com/recipes/25456/recipe_steps/48070/1601389938-33-0076-4473/1209_2P8_Pork-Pasta_384_Web.jpg"},
            {"number":"4","desc":"Finish the pasta & serve your dish",
            "step":"To the pot of cooked pasta, add the cooked sausage and vegetables and half the reserved pasta cooking water. Cook on medium-high, stirring constantly, 1 to 2 minutes, or until the pasta is coated (if necessary, gradually add the remaining cooking water to ensure the pasta is thoroughly coated). Turn off the heat. Stir in the mascarpone until combined. Taste, then season with salt and pepper if desired. Serve the finished pasta garnished with the parmesan. Enjoy!",
            "img":"https://media.blueapron.com/recipes/25456/recipe_steps/48071/1601389814-33-0075-3078/1209_2P8_Pork-Pasta_386_Web.jpg"}
        ],
        "special":"false"
    },
    {   "id":6,
        "title":"Fontina & Sourdough Grilled Cheese",
        "subtitle":"with Persimmon & Onion",
        "time":"20 min",
        "price":"Vegetarian",
        "servings":"2 Servings",
        "calories":"790 Cals/serving",
        "image":"https://media.blueapron.com/recipes/25460/square_newsletter_images/1601347875-32-0040-6048/1102_2PV1_Fontina-Grilled-Cheese_269_SQ_Web.jpg",
        "ingredients":
        [   {"qty":"4 slices","name":"Sourdough Pullman Bread"},
            {"qty":"1","name":"Red Onion"},
            {"qty":"1","name":"Persimmon"},
            {"qty":"1","name":"Watermelon Radish"},
            {"qty":"1","name":"Romaine Lettuce Heart"},
            {"qty":"4 oz","name":"Shredded Fontina Cheese"},
            {"qty":"2 Tbsps","name":"Sliced Roasted Almonds"},
            {"qty":"3 Tbsps","name":"Ranch Dressing"},
            {"qty":"1 Tbsp","name":"Sherry Vinegar"}
        ],
        "ingredientsImg":"https://media.blueapron.com/recipes/25460/ingredient_images/1601347888-32-0035-1905/1102_2PV1_Shredded_large_feature.png",
        "steps":
        [   {"number":"1","desc":"Prepare & cook the onion",
            "step":"Halve, peel, and medium dice the onion to get ½ cup (you may have extra). In a large pan (nonstick, if you have one), heat 2 teaspoons of olive oil on medium-high until hot. Add the diced onion; season with salt and pepper. Cook, stirring occasionally, 3 to 4 minutes, or until lightly browned and softened. Add the vinegar (carefully, as the liquid may splatter). Cook, stirring constantly, 30 seconds to 1 minute, or until the liquid has cooked off. Turn off the heat.",
            "img":"https://media.blueapron.com/recipes/25460/recipe_steps/48088/1601348006-32-0037-5996/1112_2PV1_Fontina-Grilled-Cheese_083_WEB.jpg"},
            {"number":"2","desc":"Prepare the remaining ingredients",
            "step":"Meanwhile, wash and dry the fresh produce. Core the persimmon; halve lengthwise, then thinly slice crosswise. Roughly chop the lettuce. Halve the radish lengthwise, then thinly slice crosswise. Combine the chopped lettuce and sliced radish in a large bowl.",
            "img":"https://media.blueapron.com/recipes/25460/recipe_steps/48089/1601347935-33-0033-3570/1102_2PV1_Fontina-Grilled-Cheese_248_Web.jpg"},
            {"number":"3","desc":"Assemble & cook the sandwiches",
            "step":"Assemble the sandwiches using the bread, cheese, sliced persimmon, and cooked onion; season with salt and pepper. Rinse and wipe out the pan used to cook the onion. In the same pan, heat 1 tablespoon of olive oil on medium until hot. Add the sandwiches; loosely cover the pan with foil and cook 2 to 4 minutes per side, or until lightly browned and the cheese is melted (if the pan seems dry, add a drizzle of olive oil before flipping). Transfer to a cutting board; immediately season with salt. Carefully halve on an angle.",
            "img":"https://media.blueapron.com/recipes/25460/recipe_steps/48090/1601348011-32-0038-8645/1112_2PV1_Fontina-Grilled-Cheese_095_WEB.jpg"},
            {"number":"4","desc":"Make the salad & serve your dish:",
            "step":"Just before serving, to the bowl of prepared lettuce and radish, add the ranch dressing and almonds. Season with salt and pepper; toss to coat. Taste, then season with salt and pepper if desired. Serve the cooked sandwiches with the salad on the side. Enjoy!",
            "img":"https://media.blueapron.com/recipes/25460/recipe_steps/48091/1601347924-32-0036-0081/1102_2PV1_Fontina-Grilled-Cheese_253_Web.jpg"}
        ],
        "special":"true"
    },

    {   "id":7,
        "title":"Pork Chops & Maple-Sage Pan Sauce",
        "subtitle":"with Roasted Brussels Sprouts & Delicata Squash",
        "time":"35 min",
        "price":"600 Calories Or Less",
        "servings":"2 Servings",
        "calories":"500 Cals/serving",
        "image":"https://media.blueapron.com/recipes/25457/square_newsletter_images/1601348389-33-0040-0363/1102_2P10_Pork-Chops-Maple-Sage_209_SQ_Web.jpg",
        "ingredients":
        [   {"qty":"2","name":"Boneless, Center-Cut Pork Chops"},
            {"qty":"1","name":"Apple"},
            {"qty":"4 oz","name":"Brussels Sprouts"},
            {"qty":"6 oz","name":"Carrots"},
            {"qty":"1 bunch","name":"Sage"},
            {"qty":"1","name":"Delicata Squash"},
            {"qty":"1.5 Tbsps","name":"Maple Syrup"},
            {"qty":"1 Tbsp","name":"Dijon Mustard"}
        ],
        "ingredientsImg":"https://media.blueapron.com/recipes/25457/ingredient_images/1601348538-32-0043-9096/1102_2PRE10_large_feature.png",
        "steps":
        [   {   "number":"1","desc":"Prepare the ingredients & start the sauce",
                "step":"Place an oven rack in the center of the oven, then preheat to 450°F. Wash and dry the fresh produce. Cut off and discard the ends of the squash; halve lengthwise. Using a spoon, scoop out the pulp and seeds; medium dice. Cut off and discard the stem ends of the brussels sprouts; quarter lengthwise. Peel the carrots; halve lengthwise, then cut crosswise into 2-inch pieces. Core and medium dice the apple. Pick the sage leaves off the stems; discard the stems and thinly slice the leaves. In a bowl, whisk together the mustard, maple syrup, and 1/4 cup of water. Season with salt and pepper.",
                "img":"https://media.blueapron.com/recipes/25457/recipe_steps/48072/1601348461-33-0042-6098/1102_2P10_Pork-Chops-Maple-Sage_172_Web.jpg"},
            {   "number":"2","desc":"Roast the vegetables",
                "step":"Place the diced squash, quartered brussels sprouts, and carrot pieces on a sheet pan. Drizzle with 1 teaspoon of olive oil and season with salt and pepper; toss to coat. Arrange in an even layer. Roast 18 to 20 minutes, or until browned and tender when pierced with a fork.",
                "img":"https://media.blueapron.com/recipes/25457/recipe_steps/48073/1601348427-33-0041-1001/1102_2P10_Pork-Chops-Maple-Sage_199_Web.jpg"},
            {   "number":"3","desc":"Cook the pork & apple",
                "step":" Meanwhile, pat the pork dry with paper towels. Season with salt and pepper on both sides. In a medium pan (nonstick, if you have one), heat 2 teaspoons of olive oil on medium-high until hot. Add the seasoned pork and diced apple in an even layer. Cook, stirring the apple occasionally, 4 to 6 minutes, or until the pork is browned. Flip the pork and loosely cover the pan with foil. Cook, without stirring, 4 to 6 minutes, or until the apple is softened and the pork is cooked through.* Leaving the apple in the pan, transfer the cooked pork to a cutting board; let rest at least 5 minutes. *An instant-read thermometer should register 145°F.",
                "img":"https://media.blueapron.com/recipes/25457/recipe_steps/48074/1601348449-32-0042-3251/1102_2P10_Pork-Chops-Maple-Sage_187_Web.jpg"},
            {   "number":"4","desc":"Finish the sauce & serve your dish",
                "step":"While the pork rests, add the sauce and sliced sage leaves to the pan of cooked apple. Cook on medium- high, stirring frequently, 1 to 2 minutes, or until the apple is thoroughly coated. Turn off the heat. Slice the rested pork crosswise. Serve the sliced pork with the roasted vegetables. Top the pork with the finished sauce and apple. Enjoy!",
                "img":"https://media.blueapron.com/recipes/25457/recipe_steps/48075/1601348517-32-0043-6243/0311_W5_Pork-Chops_0595_Web.jpg"}
        ],
        "special":"true"
    },
    
    {   "id":8,
        "title":"Spaghetti Squash, Pepper & Carrot Shakshuka",
        "subtitle":"with Za'atar Breadcrumbs & Feta Cheese",
        "time":"45 min",
        "price":"600 Calories Or Less",
        "servings":"2 Servings",
        "calories":"510 Cals/serving",
        "image":"https://media.blueapron.com/recipes/25175/square_newsletter_images/1603459309-33-0003-6086/1102_2PV3_Shakshuka_088_Web_Web.jpg",
        "ingredients":
        [
            {"qty":"2","name":"Pasture-Raised Eggs"},
            {"qty":"1","name":"8-Oz Can Tomato Sauce"},
            {"qty":"1","name":"Spaghetti Squash"},
            {"qty":"2 cloves","name":"Garlic"},
            {"qty":"6 oz","name":"Carrots"},
            {"qty":"2","name":"Scallions"},
            {"qty":"1/4 cup","name":"Panko Breadcrumbs"},
            {"qty":"1.5 oz","name":"Feta Cheese"},
            {"qty":"1 Tbsp","name":"Red Harissa Paste"},
            {"qty":"1/2 oz","name":"Sweet Piquante Peppers"},
            {"qty":"1 Tbsp","name":"Za'atar Seasoning (Ground Sumac, Sesame Seeds, Salt, Ground Thyme, Whole Dried Oregano & Crushed Aleppo Pepper)"},
            {"qty":"1","name":"Poblano Pepper"}
        ],
        "ingredientsImg":"https://media.blueapron.com/recipes/25175/ingredient_images/1601658284-34-0001-0473/1102_2PV3_large_feature.png",
        "steps":
        [   {"number":"1","desc":"Prepare & cook the spaghetti squash",
            "step":"If you prefer to use an oven to cook the squash instead of a microwave, place an oven rack in the center of the oven; preheat to 450°F. Wash and dry the fresh produce. Using a sharp, sturdy knife, carefully halve the squash lengthwise. Using a spoon, scoop out the pulp and seeds. Drizzle the cut sides with olive oil; season with salt and pepper.MICROWAVE: Working in two batches if necessary, transfer the prepared squash to a microwave-safe baking dish, cut side down. Fill with 1/2 inch of water. Microwave on high 3 to 5 minutes, or until the flesh easily pulls away from the skin. OVEN: Line a sheet pan with parchment paper (or foil). Transfer the prepared squash to the sheet pan, cut side down. Roast  25 to 30 minutes, or until the skin is lightly browned and the flesh easily pulls away from the skin.Transfer the cooked squash to a large bowl to cool slightly.",
            "img":"https://media.blueapron.com/recipes/25175/recipe_steps/47023/1601347679-32-0037-9033/Spaghetti-Squash_2P_Cooked_Microwave_0823_Web.jpg"},
            {"number":"2","desc":"Prepare the remaining ingredients",
            "step":"Meanwhile, peel the carrots; halve lengthwise, then thinly slice crosswise. Peel and roughly chop 2 cloves of garlic. Thinly slice the scallions, separating the white bottoms and hollow green tops. Roughly chop the pickled peppers. Cut off and discard the stems of the poblano pepper; remove the cores. Halve lengthwise, then thinly slice crosswise. Thoroughly wash your hands immediately after handling.",
            "img":"https://media.blueapron.com/recipes/25175/recipe_steps/47022/1601414686-33-0001-8399/1102_2PV3_Squash-Shakshuka_069_Web_poblano.jpg"},
            {"number":"3","desc":"Make the za'atar breadcrumbs",
            "step":"In a large pan (nonstick, if you have one), heat a drizzle of olive oil on medium-high until hot. Add the breadcrumbs and half the za'atar. Season with salt and pepper. Cook, stirring frequently, 2 to 3 minutes, or until toasted. Transfer to a bowl. Rinse and wipe out the pan.",
            "img":"https://media.blueapron.com/recipes/25175/recipe_steps/47025/1601347644-32-0033-7280/1102_2PV3_Squash-Shakshuka_075_Web.jpg"},
            {"number":"4","desc":"Separate the squash into strands",
            "step":"When cool enough to handle, using a fork, scrape the flesh of the cooked squash into the bowl; separate any clumps. Discard the skins.",
            "img":"https://media.blueapron.com/recipes/25175/recipe_steps/48262/1601559008-32-0012-2219/Spaghetti-Squash-Shred_Bowl_111_Web.jpg"},
            {"number":"5","desc":"Start the shakshuka",
            "step":"In the same pan, heat 2 teaspoons of olive oil on medium-high until hot. Add the sliced carrots in an even layer. Cook, without stirring, 2 to 3 minutes, or until lightly browned. Add the chopped garlic and sliced white bottoms of the scallions; season with salt and pepper. Cook, stirring  occasionally, 1 to 2 minutes, or until softened. Add the sliced poblano pepper; season with salt and pepper. Cook, stirring occasionally, 3 to 4 minutes, or until softened. Carefully add the tomato sauce, harissa paste, remaining za’atar, and 1/2 cup of water; season with salt and pepper. Cook, stirring occasionally, 2 to 3 minutes, or until thickened.",
            "img":"https://media.blueapron.com/recipes/25175/recipe_steps/47024/1603459335-32-0005-1982/1102_2PV3_Shakshuka_072_Web.jpg?width=512"},
            {"number":"6","desc":"Finish the shakshuka & serve your dish",
            "step":"Add the squash strands to the pan; stir to combine. Using a spoon, create 2 shallow wells in the center of the shakshuka. Carefully crack an egg into each well. Cover the pan with foil and cook 4 to 5 minutes, or until the egg whites are set and the yolks are cooked to your desired degree of doneness. Turn off the heat. Let stand at least 2 minutes. Serve the finished shakshuka topped with the za’atar breadcrumbs and cheese (crumbling before adding). Garnish with the sliced green tops of the scallions and chopped pickled peppers. Enjoy!",
            "img":"https://media.blueapron.com/recipes/25175/recipe_steps/47026/1603459326-33-0004-4164/1102_2PV3_Shakshuka_074_Web.jpg"}
        ],
        "special":"false"
    },
    
    {   "id":9,
        "title":"Spicy Ginger Chicken Tacos",
        "subtitle":"with Curry-Roasted Potatoes",
        "time":"30 min",
        "servings":"2 Servings",
        "calories":"680 Cals/serving",
        "image":"https://media.blueapron.com/recipes/25455/square_newsletter_images/1601390380-32-0084-5018/0113_2PRE07_Indian-Chicken-Tacos_173_201_SQ_Web.jpg",
        "ingredients":
        [   {"qty":"10 oz","name":"Chopped Chicken Breast"},
            {"qty":"4","name":"Flour Tortillas"},
            {"qty":"1/2 lb","name":"Red Cabbage"},
            {"qty":"3/4 lb","name":"Golden Potatoes"},
            {"qty":"1","name":"Piece Ginger"},
            {"qty":"1 clove","name":"Garlic"},
            {"qty":"1","name":"Bird's Eye Chile Pepper"},
            {"qty":"2 Tbsps","name":"Vegetarian Worcestershire Sauce"},
            {"qty":"1/2 cup","name":"Tzatziki (Cucumber-Yogurt Sauce)"},
            {"qty":"2 tsps","name":"Vadouvan Curry Powder"}
        ],
        "ingredientsImg":"https://media.blueapron.com/recipes/25455/ingredient_images/1601390147-32-0083-2669/1102_2PRE07_Chopped_large_feature.png",
        "steps":
        [   {"number":"1","desc":"Prepare & roast the potatoes",
            "step":"Place an oven rack in the center of the oven, then preheat to 450°F. Wash and dry the fresh produce. Cut the potatoes into 1/2-inch-thick rounds. Place on a sheet pan. Drizzle with olive oil and season with salt, pepper, and enough of the curry powder to coat (you may have extra); toss to thoroughly coat. Arrange in an even layer. Roast 19 to 21 minutes, or until browned and tender when pierced with a fork. Transfer to a bowl.",
            "img":"https://media.blueapron.com/recipes/25455/recipe_steps/48063/1601390604-33-0081-7662/0113_2PRE07_Indian-Chicken-Tacos_278.jpg"},
            {"number":"2","desc":"Prepare the remaining ingredients & make the slaw",
            "step":"Meanwhile, peel the ginger; finely chop to get 2 teaspoons (you may have extra). Peel 1 clove of garlic; using a zester, finely grate into a paste (or use the small side of a box grater). Cut out and discard the core of the cabbage; thinly slice the leaves. Place in a bowl; add the tzatziki. Season with salt and pepper; toss to coat. Set aside to marinate, stirring occasionally, at least 10 minutes. Taste, then season with salt and pepper if desired. Cut off and discard the stem of the pepper; thinly slice (for a milder dish, remove the ribs and seeds). Thoroughly wash your hands and cutting board immediately after handling.",
            "img":"https://media.blueapron.com/recipes/25455/recipe_steps/48064/1601390594-33-0080-7252/0113_2PRE07_Indian-Chicken-Tacos_253_Web.jpg"},
            {"number":"3","desc":"Cook the chicken",
            "step":"Pat the chicken dry with paper towels; season with salt and pepper. In a medium pan (nonstick, if you have one), heat 2 teaspoons of olive oil on medium-high until hot. Add the seasoned chicken in an even layer. Cook, without stirring, 3 to 4 minutes, or until lightly browned. Add the chopped ginger and as much of the sliced pepper as you’d like, depending on how spicy you’d like the dish to be. Cook, stirring occasionally, 3 to 4 minutes, or until the chicken is browned and cooked through. Turn off the heat. Stir in the worcestershire sauce, scraping up any browned bits (or fond) from the pan.",
            "img":"https://media.blueapron.com/recipes/25455/recipe_steps/48065/1601390580-33-0079-2475/0113_2PRE07_Indian-Chicken-Tacos_303_Web.jpg"},
            {"number":"4","desc":"Warm the tortillas",
            "step":"If you prefer to use a microwave, wrap the tortillas in a damp paper towel and microwave on high 1 minute, or until heated through. If you prefer to use the oven, wrap the tortillas in foil and place directly onto an oven rack; warm 7 to 9 minutes, or until heated through. Transfer the warmed tortillas to a work surface and carefully unwrap.",
            "img":"https://media.blueapron.com/recipes/25455/recipe_steps/48066/1601390705-32-0089-7460/2P_Tortilla_Papertowel_WEB.jpg"},
            {"number":"5","desc":"Finish & serve your dish",
            "step":"To the bowl of roasted potatoes, add a drizzle of olive oil and as much of the garlic paste as you’d like; toss to combine. Taste, then season with salt and pepper if desired. Assemble the tacos using the warmed tortillas, slaw, and cooked chicken. Serve the tacos with the finished potatoes on the side. Enjoy!",
            "img":"https://media.blueapron.com/recipes/25455/recipe_steps/48067/1601390557-32-0087-8248/0113_2PRE07_Indian-Chicken-Tacos_310_Web.jpg"}
        ],
        "special":"false"
    },
    
    {   "id":10,
        "title":"Smoky Seared Cod",
        "subtitle":"with Roasted Potatoes & Date Pan Sauce",
        "time":"35 min",
        "servings":"2 Servings",
        "calories":"650 Cals/serving",
        "image":"https://media.blueapron.com/recipes/25458/square_newsletter_images/1603465765-32-0016-7099/1102_2P9_Smoky-Cod_334_Web.jpg",
        "ingredients":
        [   {"qty":"2","name":"Cod Fillets"},
            {"qty":"2 oz","name":"Arugula"},
            {"qty":"1","name":"Lemon"},
            {"qty":"2 cloves","name":"Garlic"},
            {"qty":"3/4 lb","name":"Golden Potatoes"},
            {"qty":"2 Tbsps","name":"Sliced Roasted Almonds"},
            {"qty":"1 oz","name":"Dried Medjool Dates"},
            {"qty":"1","name":"Shallot"},
            {"qty":"2 Tbsps","name":"Butter"},
            {"qty":"1 Tbsp","name":"Sherry Vinegar"},
            {"qty":"1/4 cup","name":"Rice Flour"},
            {"qty":"2 tsps","name":"Honey"},
            {"qty":"1 Tbsp","name":"Smoky Spice Blend (Smoked Paprika, Sweet Paprika, Ground Yellow Mustard, Garlic Powder & Onion Powder)"}
        ],
        "ingredientsImg":"https://media.blueapron.com/recipes/25458/ingredient_images/1601662645-32-0007-3385/1102_2PRE09_large_feature.png",
        "steps":
        [
            {"number":"1","desc":"Prepare the ingredients",
            "step":"Remove the honey from the refrigerator to bring to room temperature. Place an oven rack in the center of the oven; preheat to 450°F. Wash and dry the fresh produce. Cut the potatoes into 1/4-inch-thick rounds. Peel and thinly slice the shallot. Peel and roughly chop 2 cloves of garlic. Pit and roughly chop the dates. Quarter and deseed the lemon.",
            "img":"https://media.blueapron.com/recipes/25458/recipe_steps/48076/1601059247-32-0001-3826/313-2PF-Smoky-Seared-Cod-26603_WEB_NoGreens.jpg"},
            {"number":"2","desc":"Roast the potatoes",
            "step":"Place the potato rounds on a sheet pan. Drizzle with 2 teaspoons of olive oil and season with salt and pepper; toss to coat. Arrange in an even layer. Roast 18 to 20 minutes, or until lightly browned and tender when pierced with a fork. Transfer to a large bowl.",
            "img":"https://media.blueapron.com/recipes/25458/recipe_steps/48077/1601388787-33-0072-4027/313-2PF-Smoky-Seared-Cod-26605_WEB.jpg"},
            {"number":"3","desc":"Pickle the shallot",
            "step":"Meanwhile, in a small pot, combine the sliced shallot, honey (kneading the packet before opening), vinegar and ¼ cup of water; season with salt and pepper. Heat to boiling on high. Once boiling, cook, stirring occasionally, 1 to 2 minutes, or until combined and the shallot is coated. Turn off the heat. Set aside to cool at least 10 minutes. Taste, then season with salt and pepper if desired.",
            "img":"https://media.blueapron.com/recipes/25458/recipe_steps/48078/1603465792-32-0018-9062/1102_2P9_Smoky-Cod_321_web.jpg"},
            {"number":"4","desc":"Coat & start the fish",
            "step":"Meanwhile, on a large plate, combine the flour and spice blend. Pat the fish dry with paper towels. Season on both sides with salt and pepper. Working one piece at a time, thoroughly coat the seasoned fish in the seasoned flour (shaking off any excess flour). In a medium pan (nonstick, if you have one), heat 1 tablespoon of olive oil on medium-high until hot. Add the coated fish. Cook 2 to 3 minutes, or until browned.",
            "img":"https://media.blueapron.com/recipes/25458/recipe_steps/48079/1603465786-32-0017-3965/1102_2P9_Smoky-Cod_310_web.jpg"},
            {"number":"5","desc":"Make the sauce & finish the fish",
            "step":"Flip the fish and add the butter, chopped garlic, chopped dates, and 1/4 cup of water (carefully, as the liquid may splatter) to the pan; season with salt and pepper. Cook, occasionally spooning the sauce over the fish, 2 to 4 minutes, or until the fish is coated and cooked through.* Turn off the heat. Evenly top with the juice of 2 lemon wedges. Taste, then season with salt and pepper if desired.  *An instant-read thermometer should register 145°F.",
            "img":"https://media.blueapron.com/recipes/25458/recipe_steps/48080/1603465780-33-0018-2997/1102_2P9_Smoky-Cod_315_web.jpg"},
            {"number":"6","desc":"Finish the vegetables & serve your dish",
            "step":"Reserving 2 tablespoons of the shallot pickling liquid, drain the pickled shallot. To the bowl of roasted potatoes, add the arugula, pickled shallot, reserved pickling liquid, the juice of the remaining lemon wedges, and a drizzle of olive oil. Toss to combine. Taste, then season with salt and pepper if desired. Serve the finished vegetables topped with the cooked fish and sauce. Garnish with the almonds. Enjoy!",
            "img":"https://media.blueapron.com/recipes/25458/recipe_steps/48081/1601388744-33-0069-4344/313-2PF-Smoky-Seared-Cod-26712_WEB.jpg"}
        ],
        "special":"false"
    }
];

export const displayFood=[
    {   "id":1,
        "title":"Dijon & Panko-Crusted Lamb Chops",
        "subtitle": "with Salsa Verde Carrots & Garlicky Purple Potatoes",
        "time":"55 min",
        "price":"$19.99/SERVING",
        "servings":"2 Servings", 
        "calories":"940 Cals/serving", 
        "image": "https://media.blueapron.com/recipes/25448/square_newsletter_images/1601348202-32-0039-4337/1102_2P12_Herb-Crusted-Lamb_374_SQ_Web.jpg", 
        "ingredients":
            [   {"qty": "1","name":"Frenched Rack Of Lamb"},
                {"qty":"6 oz","name": "Carrots"},
                {"qty":"3/4 lb","name":"Purple Potatoes"},
                {"qty":"1","name":"Lemon"},
                {"qty":"2 cloves", "name": "Garlic"},
                {"qty":"1 bunch", "name": "Thyme"},
                {"qty":"1 bunch", "name": "Oregano"},
                {"qty":"1/4 cup", "name": "Panko Breadcrumbs"},
                {"qty":"1 Tbsp", "name": "Dijon Mustard"},
                {"qty":"1/3 cup", "name": "Salsa Verde"},
                {"qty":"0.7 oz", "name": "Grana Padano Cheese"},
                {"qty":"2 Tbsps", "name": "Crème Fraiche"},
                {"qty":"1 oz", "name": "Castelvetrano Olives"}
            ],
        "ingredientsImg":"https://media.blueapron.com/recipes/25448/ingredient_images/1601659427-32-0002-5216/1102_2PRE12_large_feature.png",
        "steps":
            [   {"number":"1","desc":"Prepare the ingredients", 
                "step":"Preheat the oven to 450°F. Wash and dry the fresh produce. Peel the carrots; halve lengthwise, then halve crosswise. Halve the potatoes lengthwise; cut crosswise into 1/4-inch pieces. Pick the thyme leaves off the stems. Quarter and deseed the lemon. Peel 2 cloves of garlic; using a zester, finely grate into a paste (or use the small side of a box grater). Pick the oregano leaves off the stems; finely chop. Pit and roughly chop the olives. Grate the cheese on the small side of a box grater. In a bowl, combine the breadcrumbs, thyme leaves, half the garlic paste, half the mustard, and 2 teaspoons of olive oil; season with salt and pepper. To make the garlic dressing, in a separate, large  bowl, combine the chopped oregano, chopped olives, remaining garlic paste, the juice of 2 lemon wedges, and a drizzle of olive oil; season with salt and pepper. In a separate bowl, combine the crème fraîche and salsa verde.",
                "img":"https://media.blueapron.com/recipes/25448/recipe_steps/48670/1601348264-33-0037-6769/1102_2P12_Herb-Crusted-Lamb_102_Web.jpg"}, 
                {"number":"2","desc":"Prepare & roast the lamb",
                "step":"Line a sheet pan with foil. Pat the lamb dry with paper towels; season with salt and pepper on all sides. Place on the sheet pan, bone side down. Evenly spread or brush the remaining mustard onto the top side of the lamb (opposite of the bones), then top with the breadcrumb mixture (pressing to adhere). Roast 27 to 29 minutes for medium (125°F), or until cooked to your desired degree of doneness.* Transfer to a cutting board and let rest at least 10 minutes.*The USDA recommends cooking lamb until an instant-read thermometer registers a minimum temperature of 145°F.",
                "img":"https://media.blueapron.com/recipes/25448/recipe_steps/48671/1601348259-33-0036-5606/1102_2P12_Herb-Crusted-Lamb_103_Web.jpg"},
                {"number":"3","desc":"Roast the vegetables",
                "step":"Meanwhile, transfer the carrot pieces to one side of a separate sheet pan; place the potato pieces on the other side. Drizzle with olive oil and season with salt and pepper. Toss to coat; keeping them separate on the sheet pan, arrange in an even layer. Roast 20 to 22 minutes, or until browned and tender when pierced with a fork. Remove from the oven.",
                "img":"https://media.blueapron.com/recipes/25448/recipe_steps/48672/1601348255-32-0040-6043/1102_2P12_Herb-Crusted-Lamb_104_Web.jpg"},
                {"number":"4","desc":"Dress the vegetables",
                "step":"Transfer the roasted carrots to a large bowl; add half the creamy salsa verde. Toss to coat. Taste, then season with salt and pepper if desired. Transfer the roasted potatoes to the bowl of garlic dressing; add the grated cheese. Toss to combine. Taste, then season with salt and pepper if desired.",
                "img":"https://media.blueapron.com/recipes/25448/recipe_steps/48673/1601348239-33-0035-0638/1102_2P12_Herb-Crusted-Lamb_105_Web.jpg"},
                {"number":"5","desc":"Slice the lamb & serve your dish",
                "step":"Slice the rested lamb  between each bone. Serve the sliced lamb with the remaining creamy salsa verde. Serve the dressed carrots, dressed potatoes, and remaining lemon wedges on the side. Enjoy!",
                "img":"https://media.blueapron.com/recipes/25448/recipe_steps/48674/1601348235-32-0042-5502/1102_2P12_Herb-Crusted-Lamb_106_Web.jpg"}
            ],
        "special":"false"
    },
    {   "id":2,
        "title":"Calabrian Shrimp & Orzo",
        "subtitle":"with Tomatoes & Parmesan Cheese",
        "time":"20 min",
        "price":"600 Calories Or Less",
        "servings":"2 Servings",
        "calories":"500 Cals/serving",
        "image":"https://media.blueapron.com/recipes/25451/square_newsletter_images/1603459980-33-0011-6659/1102_2PF_Shrimp_0480_SQ_Web.jpg",
        "ingredients":
        [   {"qty":"10 oz","name":"Tail-On Shrimp (Peeled & Deveined)"},
            {"qty":"4 oz","name":"Orzo Pasta"},
            {"qty":"2 cloves","name":"Garlic"},
            {"qty":"1","name":"Lemon"},
            {"qty":"1.5 tsps","name":"Calabrian Chile Paste"},
            {"qty":"2 Tbsps","name":"Crème Fraîche"},
            {"qty":"1 Tbsp","name":"Capers"},
            {"qty":"1/4 cup","name":"Grated Parmesan Cheese"},
            {"qty":"4 oz","name":"Grape Tomatoes"}
        ],
        "ingredientsImg":"https://media.blueapron.com/recipes/25451/ingredient_images/1601343193-32-0003-8741/1102_2PF_large_feature.png",
        "steps":
        [   {"number":"1","desc":"Prepare the ingredients",
            "step":"Fill a medium pot 3/4 of the way up with salted water; cover and heat to boiling on high. Wash and dry the fresh produce. Halve the tomatoes. Quarter and deseed the lemon. Peel and roughly chop 2 cloves of garlic. Pat the shrimp dry with paper towels; remove the tails. Place in a bowl; add the chopped garlic, capers, and as much of the chile paste as you’d like, depending on how spicy you’d like the dish to be. Drizzle with olive oil and season with salt and pepper. Stir to combine.",
            "img":"https://media.blueapron.com/recipes/25451/recipe_steps/48046/1601415440-33-0003-2981/1102_2PF_Calabrian-Shrimp-Orzo_102_Web_Tomato.jpg"},
            {"number":"2","desc":"Cook the pasta",
            "step":"Add the pasta to the pot of boiling water and cook, uncovered, 7 to 9 minutes, or until tender. Turn off the heat. Drain thoroughly and return to the pot.",
            "img":"https://media.blueapron.com/recipes/25451/recipe_steps/48047/1601343371-32-0010-5622/0121_2PF-WW2_Shrimp-Orzo_0541_Web.jpg"},
            {"number":"3","desc":"Cook the shrimp & tomatoes",
            "step":"Meanwhile, in a large pan (nonstick, if you have one), heat 2 teaspoons of olive oil on medium-high until hot. Add the prepared shrimp in an even layer. Cook, without stirring, 2 to 3 minutes, or until lightly browned. Add the halved tomatoes. Cook, stirring frequently, 1 to 2 minutes, or until the shrimp are opaque and cooked through. Turn off the heat.",
            "img":"https://media.blueapron.com/recipes/25451/recipe_steps/48048/1603459993-32-0013-9081/1102_2PF_Shrimp_0477_Web.jpg"},
            {"number":"4","desc":"Finish & serve your dish",
            "step":"To the pot of cooked pasta, add the cooked shrimp and tomatoes, crème fraîche, and the juice of 2 lemon wedges. Stir to combine. Taste, then season with salt and pepper if desired. Serve the finished shrimp and pasta garnished with the cheese and remaining lemon wedges. Enjoy!",
            "img":"https://media.blueapron.com/recipes/25451/recipe_steps/48050/1603460000-33-0012-4002/1102_2PF_Shrimp_0482_Web.jpg"}
        ],
        "special":"true"
    },
    {   "id":3,
        "title":"Mongolian Beef & Noodles",
        "subtitle":"with Shishito Peppers & Scallions",
        "time":"25 min",
        "servings":"2 Servings",
        "calories":"650 Cals/serving",
        "image":"https://media.blueapron.com/recipes/25450/square_newsletter_images/1603459639-32-0007-3159/1102_2P11_Mongolian-Beef_0489_SQ_Web.jpg",
        "ingredients":
        [   {"qty":"8 oz","name":"Thinly Sliced Beef"},
            {"qty":"6 oz","name":"Fresh Wonton Noodles (PreviouslyFrozen)"},
            {"qty":"2 cloves","name":"Garlic"},
            {"qty":"2","name":"Scallions"},
            {"qty":"1 Tbsp","name":"Soy Sauce"},
            {"qty":"1 Tbsp","name":"Light Brown Sugar"},
            {"qty":"1/4 cup","name":"Cornstarch"},
            {"qty":"1","name":"Piece Ginger"},
            {"qty":"2 Tbsps","name":"Chicken Demi-Glace"},
            {"qty":"3 oz","name":"Shishito Peppers"},
            {"qty":"1/4 tsp","name":"Crushed Red Pepper Flakes"}
        ],
        "ingredientsImg":"https://media.blueapron.com/recipes/25450/ingredient_images/1601387630-32-0071-9898/1102_2PRE11_large_feature.png",
        "steps":
        [   {"number":"1","desc":"Prepare the ingredients",
            "step":"Fill a medium pot 3/4 of the way up with salted water; cover and heat to boiling on high. Wash and dry the fresh produce. Peel and roughly chop 2 cloves of garlic. Peel the ginger; finely chop to get 2 teaspoons (you may have extra). Slice the scallions into 1/2-inch pieces, separating the white bottoms and hollow green tops. Cut off and discard the stems of the peppers; cut crosswise into 1/2-inch pieces. Thoroughly wash your hands, knife, and cutting board immediately after handling. Place the pepper pieces in a bowl; add the chopped garlic, chopped ginger, and sliced white bottoms of the scallions.",
            "img":"https://media.blueapron.com/recipes/25450/recipe_steps/48040/1603459664-33-0007-3219/1102_2P11_Mongolian-Beef_0473_Web.jpg"},
            {"number":"2","desc":"Make the sauce",
            "step":"In a bowl, combine the soy sauce, demi-glace, sugar, 1/3 cup of water, and as much of the red pepper flakes as you’d like, depending on how spicy you’d like the dish to be.",
            "img":"https://media.blueapron.com/recipes/25450/recipe_steps/48041/1601387551-32-0072-3247/1019_FP5_Mongolian-Beef_028_Web.jpg"},
            {"number":"3","desc":"Cook the peppers",
            "step":"In a medium pan (nonstick, if you have one), heat 2 teaspoons of olive oil on medium-high until hot. Add the prepared pepper mixture; season with salt and pepper. Cook, stirring frequently, 3 to 4 minutes, or until softened. Transfer to a plate. Wipe out the pan.",
            "img":"https://media.blueapron.com/recipes/25450/recipe_steps/48042/1603459683-32-0008-0191/1102_2P11_Mongolian-Beef_0478_Web.jpg"},
            {"number":"4","desc":"Cook the beef",
            "step":"Separate the beef; pat dry with paper towels. Place in a bowl and season with salt and pepper. Add the cornstarch; toss to thoroughly coat. In the same pan, heat 2 teaspoons of olive oil on medium-high. Once the oil is hot enough that a pinch of cornstarch sizzles immediately when added, add the coated beef in an even layer (discarding any excess cornstarch). Cook, without stirring, 2 to 3 minutes, or until lightly browned. Continue to cook, stirring frequently, 1 to 2 minutes, or until browned and just cooked through. Turn off the heat.",
            "img":"https://media.blueapron.com/recipes/25450/recipe_steps/48043/1601660392-34-0004-0013/1028_2PRE10_WW05_Spicy-Pepper-Beef_120_Web.jpg"},
            {"number":"5","desc":"Cook the noodles",
            "step":"Meanwhile, add the noodles to the pot of boiling water, stirring gently to separate. Cook, stirring occasionally, 2 to 4 minutes, or until tender. Turn off the heat. Drain thoroughly and return to the pot.",
            "img":"https://media.blueapron.com/recipes/25450/recipe_steps/48044/1601387535-32-0068-3165/1019_FP5_Mongolian-Beef_044_Web.jpg"},
            {"number":"6","desc":"Finish the noodles & serve your dish",
            "step":"To the pot of cooked noodles, add the cooked vegetables, cooked beef, and sauce. Cook on medium-high, stirring constantly, 1 to 2 minutes, or until coated. Turn off the heat; taste, then season with salt and pepper if desired. Serve the finished noodles garnished with the sliced green tops of the scallions. Enjoy!",
            "img":"https://media.blueapron.com/recipes/25450/recipe_steps/48045/1603459691-32-0009-1382/1102_2P11_Mongolian-Beef_0481_Web.jpg"}
        ],
        "special":"false"
    }
]